### ISSUE TITLE
Regions in WIEGO map don't change color of countries

### ISSUE THREAD

**Issue by numeroteca** [WIEGO-Global/wiegodashboard#1]
When selecting “South Asia” from the menu drop-down. None of the countries change to green like they do for East Asia & Southeast Asia. In fact, most of the regions when selected from the drop-down menu do not display the respective countries in green.
![east-se-asia-wiego-presence](https://cloud.githubusercontent.com/assets/1223722/18305122/4e67dbda-74e6-11e6-932b-9251d5b55c7a.jpg)
![south-asia-wiego-presence](https://cloud.githubusercontent.com/assets/1223722/18305123/4e6a24ee-74e6-11e6-9fc3-a16ee4d5abcf.png)

**Comment by numeroteca** [comment]
I've made a new test in the production server and it is not working. Also not working for Africa.

**Comment by numeroteca** [comment]
This is fixed.

**Comment by numeroteca** [comment]
No, this is not closed, it is not solved for a lot of regions.

**Comment by garygoldman** [comment]
This has been fixed.
