### ISSUE TITLE
View all publications & resources 

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#10]
The functionality for this needs to be built.
option number 1 in this current phase:
to have a new link that says View All, but that would take users to a new page with no Featured sidebar and no region/country dropdown - however, it will allow users to see all publications/resources.

**Comment by numeroteca** [comment]
Note for @wiegoglobal: when writing "#1" github thinks that you are providing a link to "issue 1".

**Comment by wiegoglobal** [comment]
An "All" option has been added to the dropdown menu item in publications. The filters appear . Does this mean that the list can be filtered?

**Comment by garygoldman** [comment]
This issue has been fixed. The list can be filtered.

**Comment by wiegoglobal** [comment]
This is GREAT that you were able to devise a solution, thank you!!!!
