### ISSUE TITLE
Dashboard Landing page - 1) Regions and colors are problematic; 2) missing info in sidebar

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#11]
Regions east asia and southeast asia
no map appears, at all

South Asia - not all countries change to green
sidebar: info missing for wiego presence

Latin America and Caribbean
not all countries in region change to green
sidebar: info missing for wiego presence

Middle East and North Africa
seems ok, but we have only one country with data from that region (Turkey)
information for wiego presence is missing

Sub-Saharan Africa
many countries do not change green
WIEGO Presence info does not appear in sidebar

**Comment by wiegoglobal** [comment]
Has this been fixed?

**Comment by garygoldman** [comment]
This issue has been fixed.

**Comment by wiegoglobal** [comment]
The regions all seem to color the correct countries now and maps appear. 
There are still a couple of issues:
1) Occupational groups in sidebar, Latin America: Only one occupational group is listed. There should be at least two - if not more - occupational groups listed because we have a lot of waste picker content in both WIEGO presence and publications that are in latin america. Right now only street vendors appear.

2) List of occupational groups should be listed alphabetically.

**Comment by wiegoglobal** [comment]
![alphabetize-occ-grps](https://cloud.githubusercontent.com/assets/22031182/18567496/cc25ae60-7b6e-11e6-80f2-1d57fef90df1.jpg)
![la-region-occ-grps](https://cloud.githubusercontent.com/assets/22031182/18567495/cbd098b2-7b6e-11e6-9ddc-144e5e570a7c.jpg)

**Comment by garygoldman** [comment]
We have reviewed the content added from the backend and gone through the countries of “Latin America & the Caribbean” in WIEGO presence. There are the data for “Programme Activities & Partners” and “Institutional Members”. But in “Institutional Members”, you didn’t select any occupational group.  We randomly checked 12-15 countries. Have a look on below URLs for the reference
 
http://wiego.org/node/53181/edit?destination=admin%2Fcontent%2Fnode%2Foverview
http://wiego.org/node/53236/edit?destination=admin%2Fcontent%2Fnode%2Foverview
http://wiego.org/node/53231/edit?destination=admin%2Fcontent%2Fnode%2Foverview
 
Please  provide the URLs from WIEGO Presence, for “Latin America & the Caribbean” countries where you have selected waste picker.

We will have the list of occupational groups alphabetized by early next week.
