### ISSUE TITLE
WIEGO Presence - backend - titles for each group of fields are still missing

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#13]
We had asked about this a couple of weeks ago. I seem to recall being told it would be visible with certain permission settings but I have never seen it.

see: http://wiego.org/node/add/wiego-presence

First group should have title "Institutional Members"
Second Group should have title "Individual Members"
Third Group should have title "Board Members"
Fourth Group should have title "WIEGO Team"
Fifth Group should have title "Programme Activities & Partners
         also, replace "name& title" with Programme Name (name & title does not makes sense for this section)

**Comment by wiegoglobal** [comment]
Gary indicated last week that he would ask CSF to apply this to several roles. Has this been done yet>

**Comment by garygoldman** [comment]
This issue has been fixed. First group now has title "Institutional Members," etc.

**Comment by wiegoglobal** [comment]
This issue has not been fixed.
Please make sure titles appear for the following roles:
Content Admin
Content Contributor
Wiego Admin
administrator

Please check permissions. Gary, you and I discussed this last week where you said you would speak with developers about making sure the permissions would be the same for the various roles for the wiego presence content type.

**Comment by garygoldman** [comment]
The name under Programme Activities and Partners has been changed:

![screen shot 2016-09-16 at 10 59 40 am](https://cloud.githubusercontent.com/assets/6609331/18590407/b4341326-7bfc-11e6-8ec0-51ddb7312d3f.png)

We have also updated the permissions for WIEGO Presence for the given roles. Please check and confirm.

**Comment by wiegoglobal** [comment]
The titles do not appear for the role "content administrator" - they should.
They should appear for the following roles: admin, wiego admin, content contributor, content administrator.

Thanks

**Comment by garygoldman** [comment]
This issue has been fixed.
