### ISSUE TITLE
Additonal content types missing fields in the forms

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#14]
We are certain that this issue was brought on due to the deployment of the dashboard tool. Permissions have changed and access is problematic. Now I am told that blog posts cannot be published nor can homepage feature items.

Megan Macleod will be adding comments to this issue, providing more details.

This is when someone is creating new content -there are a number of features missing that used to be present for the following additional content types

blog and homepage slider for people with permissions set to:
- content admin and content contributor and administrator

When "WIEGO admin" was added some additional features appeared but there are many items still missing that used to be available.

From the content contributor
_**For the blog:**_

_1. Authoring Info (I don't use this - it just shows who the creator (not the writer) of the blog post is - me)
2. Publishing info (I think the name isn't right, but this is the menu that allows me to publish the blog, promote it too [sic] the front page of the blog, and add a sticky to the lists, etc.)
3. Additional tagging (I think - I don't use this one either)_

_**For the slider:**_

_1. Authoring info (same as above)_
_2. Publishing info (same as above)_

_The important one for me for both of these is number 2, the publishing options. I can save changes by pressing the save button, but in order to publish, I need publishing options._

**Comment by MegMacL** [comment]
Not sure how much detail you need, but here's whats been happening on my end:

I noticed the issue last Thursday when I was publishing a blog and slider. I tried to publish through the Content List page then but although it would take me to "Performing Publish Post on selected items" page and show the loading bar, it would never go any further. It stays on 0% no matter how long I wait or how many other tabs I close. 
However, I was still able to go into the individual editing pages to publish that way until today when the the features mentioned above vanished.

I can still go in and create/edit sliders and blog posts, but I cannot publish them.

**Comment by wiegoglobal** [comment]
This is still a problem. I no longer can choose publishing options in my role. (pat_carney)

**Comment by garygoldman** [comment]
Is this only affecting the production server, or the development server as well? It would be tremendously helpful to get screenshots of the issue.

**Comment by wiegoglobal** [comment]
Hi Gary,  I'm following up with login info to troubleshoot the permissions issues we are having and other difficulties with the admin since the deployment of the site.

user:
pat_carney
pw: StreetVendor5!

roles: Admin, WIEGO Admin, Content Admin.
By adding "Content Admin." as a role I can now access the shortcut menu in the right hand sidebar.
I also have viewing access to this link wiego.org/cadmin/content
BIG PROBLEM:  I am unable to unpublish items. Also I can no loner delete from the wiego.org/cadmin/content view. The only way to delete is to go into edit mode for the individual node. I can only delete; I cannot unpublish.  **This is a problem.** We need to be able to unpublish from this view:


Here is the account that is only admin:
wiego_post
pw Testing1234!

The only way something can be published or unpublished is in edit mode in the node itself; the functionality does not work on the wiego.org/cadmin/content page

Gary, the permissions are all messed up and it's quite complicated to explain the nuanced differences and how functionality in the backend has changed with problems since the deployment. It's a bit cumbersome communicating through the channel of taking screen shots, writing here, and then trying to explain it in words over Skype, where in turn you convey the info to the developers.

Given that I am about to be leaving for almost three weeks, and have other tasks I need to complete before leaving, I don't have a whole lot of time to troubleshoot this issue. If we haven't resolved this by Thursday I request that CSF commit to resolving this with me upon my return to the office Oct. 13
![permissionsa](https://cloud.githubusercontent.com/assets/22031182/18678307/9f0b6136-7f29-11e6-88d6-4739399866c3.jpg)
.

Thank you

**Comment by wiegoglobal** [comment]
the other problem with the sole role of administrator is that the shortcut sidebar is missing.
