### ISSUE TITLE
Sidebar Expanded list collapses when someone clicks on a link - can we keep it expanded

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#15]
See:

http://wiego.org/dashboard/wiego-presence/other-developed/united-states-america

This is a functionality problem in that if someone clicks on one of the items from the expandable list, the list automatically collapses and when the person goes back to that page, the list no longer appears.

Can we keep the list expanded? Otherwise I think people will get very frustrated with the interface.

**Comment by wiegoglobal** [comment]
Recommendation from CSF one week ago was to have the link open in a new window.  This has not been applied yet.

**Comment by garygoldman** [comment]
It will not be easy to keep list expended when users go back to the page. Another solution would be to show the list always in expended form? Please suggest.

**Comment by wiegoglobal** [comment]
Gary, we had discussed the option of changing the code so that when someone clicks on the link  the code would include: target="_blank"

That is an option you and I discussed a week ago. Please ask the developers to change to link to include: target="_blank"

**Comment by garygoldman** [comment]
Apologies, this was not what I had understood from your initial comment. We will implement this ASAP.

**Comment by garygoldman** [comment]
We have updated the functionality as per the requirement. 
http://wiego.org/dashboard/wiego-presence/south-asia/india
 
As per the implemented functionality, clicking opens a new window (HTML4) or a new browsing context (HTML5). However, browsing context in modern browsers is mostly "new tab" instead of "new window". CSF has no influence on that, and we can't "force" the browser to open a new window with HTML. The modern browser has complete control over this behavior (feel free to ask Pablo if you'd like further clarification).

**Comment by wiegoglobal** [comment]
Given this new information that there is no control over having the page open in a new window vs. opening in a new tab, we should revert to the other way (click on link and it opens in the same window - not new tab, not new window).  This is based on our audience - many will not know that the page has opened in a new tab and therefore will never see the information thinking that nothing has changed upon click and will think it's broken.

The request to change to open in new window was based on not knowing about the proclivities of more recent versions of browsers' behavior.

Please confirm that it will change back.  Again, the request to open in new window was based on the understanding that this could be done. Now, hearing that the new page will open in a new tab that will not work.

Thanks,

**Comment by wiegoglobal** [comment]
My apologies for all of the back and forth on this; I thought that the tab would open behind the browser window that was already opened, but I just tested the link from three current browsers from an Apple computer and the new tab opens on top. If this tends to be the typical behavior of the newer browsers - that the new window opens as a tab in front of the previous window, then I think that would be ok.  At this point we really won't know until our audience uses the tool and provides feedback. Given this new discovery, why don't we leave as is and see what follows from our audience.

Sorry again for all of the confusion on this item.

**Comment by garygoldman** [comment]
Done - we've left it as is!
