### ISSUE TITLE
language filter in publications & resources

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#18]
The majority of our wiego publications and resources that are in English were not tagged as such. The default language is English, without needing to specify, in our current taxonomy/tagging system.

Sometimes it appears that content contributors tagged items in English but that is more the exception than the rule.

As a result, many items in English do not appear if someone chooses to filter by "English." For example, we have many, many WIEGO briefs but when I choose wiego briefs under "All" and choose the additional filter in English, the results only display 3 items.

Can you configure the "English" option in the dropdown to display any publications or resources tagged as WIEGO, with the language option "none selected."  Please see screen shot.

**Comment by wiegoglobal** [comment]
![english-filter](https://cloud.githubusercontent.com/assets/22031182/18568329/1ee3fbda-7b73-11e6-96ad-bfcec1f2e160.jpg)

**Comment by garygoldman** [comment]
We understand the issue. If no language is associated with a publication/resource, automatically having it as English would require us to make a modification in the developed functionality to change the filtering behavior. This is feasible only if you tag the content as 'English.'
