### ISSUE TITLE
Drop down menu of countries and regions

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#19]
Maps and pull-down menu usability. If we don’t have any information for a country or region, can it be greyed out/non-selectable)?

This was a comment from someone on the dataviz team. I am guessing no, because the drop down menu is the same for all three sections and the greyed out countries would not be the same across the board.

**Comment by garygoldman** [comment]
Would the grey appear on the map? As of now, countries with no info appear as white. For the dropdown, I believe you may be right - let me ask, though.

**Comment by garygoldman** [comment]
Dear Patricia,

As promised, I asked about the technical feasibility of only showing geographical areas that had data against them; and as suspected, it would require a large undertaking. 

We are showing the countries directly from the backend, added in taxonomy. To filter the drop down on the basis on available data, we would have to apply different type of checks (and do so for each section). The dropdown functionality is common to all sections, and this would indeed require each page to have its own functionality handled separately. 
 
I suggest we close this issue (perhaps to revisit in Phase 2?).
