### ISSUE TITLE
Grammatical correction

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#22]
![is-to-are](https://cloud.githubusercontent.com/assets/22031182/18572641/534e3ce4-7b93-11e6-8f22-0ad3d8253955.jpg)

(see screen shot):

1. Please change "is" to "are"
2. Add "s" to "Publication"

Should read: There are no Publications/Resources for this region/country.

**Comment by garygoldman** [comment]
This has been fixed. Check here: http://wiego.org/dashboard/publications-resources/latin-america-caribbean/guyana
