### ISSUE TITLE
Final Documentation required

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#23]
Per discussion with Gary, we need documentation that explains where the various components of the dashboard tool can be found on the backend:

- documentation on making adjustments to drop-down menu on map
- location of shapefile
- see also previous issue posted about access to GIT and the control version system

Also:

From Annex A:
Please provide the following:
"The Control Version System (CVS) that will be used is Git, and CSF will provide access to it to the WIEGO focal points"
- Do we need to have CSF's login credentials for their Git account on our server, or will we have the same access to the information using our own wiego login credentials for Git?

[Annex A-CSF- WIEGO comments - CSF Comments_GG_r2-2 plus PB.docx](https://github.com/WIEGO-Global/wiegodashboard/files/459480/Annex.A-CSF-.WIEGO.comments.-.CSF.Comments_GG_r2-2.plus.PB.docx)

**Comment by garygoldman** [comment]
Dear Patricia,

Understood. The documentation will address these three points (also touching upon a list of the elements from the backend appearing on the frontend). We will send shortly.

**Comment by garygoldman** [comment]
Dear all,

Please find attached the documentation in PDF and doc. 

[WIEGO Dashboard - Documentation.pdf](https://github.com/WIEGO-Global/wiegodashboard/files/489848/WIEGO.Dashboard.-.Documentation.pdf)
[WIEGO Dashboard - Documentation.docx](https://github.com/WIEGO-Global/wiegodashboard/files/489849/WIEGO.Dashboard.-.Documentation.docx)

**Comment by numeroteca** [comment]
Thanks, though I can't see there the access to the git repository (#4). Am I missing something?

**Comment by garygoldman** [comment]
No worries, it can be confusing. The last part of the user guide showcases the information on Acquia, which is what is used for development and where you can download the files.

**Comment by garygoldman** [comment]
Updated user guide:

[WIEGO - User Guide.docx](https://github.com/WIEGO-Global/wiegodashboard/files/495522/WIEGO.-.User.Guide.docx)
[WIEGO - User Guide.pdf](https://github.com/WIEGO-Global/wiegodashboard/files/495523/WIEGO.-.User.Guide.pdf)

**Comment by numeroteca** [comment]
Thanks Gary. 
To keep the documents up to date it would be great to open a google document with the documentation, as it is stated in the annex A. It will allow us to always access the updated documentation and clarify and comment in the same document:

> 
Training. With regard to the management of the one-­‐stop shop dashboard (i.e., updating WIEGO in the World, statistics, uploading publications and any other content),   training may be required of CSF if the management  and  method  of updating  go  beyond  what  WIEGO  has  in  place  with  its  current  Drupal system. Activity 2 will include a virtual two-­‐hour capacity-­‐building session on updating the publications and the resources sections. Activity 3 will include two virtual capacity-­‐building session, each ranging from one to two hours, on updating  the  statistics  dashboard.  The  sessions  will  be  recorded  so  it  can  be  shared  with  other members of the team. In addition to these sessions, **CSF will start a Google Document with basic information and guidance on updating the system**, which WIEGO will have editing capabilities for.

**Comment by garygoldman** [comment]
Dear Pablo,

Good point. We've uploaded the user guide to Google Drive and updated the last section with the latest instructions for git.

https://docs.google.com/document/d/1Ks4-CWs_9t05awELAEBlkZaUkkFaILs7ynITp84emZk/edit#

Feel free to share this with the rest of the team.

**Comment by numeroteca** [comment]
Thanks, I'll share this link with the rest of the team.
