### ISSUE TITLE
Featured items in pubs and resources

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#25]
There was nothing appearing under featured for the middle east and north africa region for pubs and resources. See:
http://wiego.org/dashboard/publications-resources/middle-east-north-africa

So I selected a couple of items in the region and marked them as featured. I cleared the history/cache and still those items selected as featured do not appear in the sidebar under "featured"

Here are the items that have been marked as featured:
http://wiego.org/resources/myths-facts-about-home-based-workers
http://wiego.org/resources/wiegos-law-and-informality-work 

In both cases, these items are tagged with multiple regions.  Please would you check to make sure there is not a conflict when the scenario of multiple regions are selected.

Thanks,

**Comment by garygoldman** [comment]
Dear Patricia,

This issue has been fixed. You may check: http://wiego.org/dashboard/publications-resources/middle-east-north-africa. You are correct that this was happening when items were tagged as featured with multiple regions.
