### ISSUE TITLE
4 countries are missing in Statistics

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#26]
Hi Gary,

On the statistics map the following four countries are not colored and they should be, as there is data in the sheetnode:

Bolivia
Venezuela, Bolivarian Republic of
The Former Yugoslav Republic of Macedonia
The State of Palestine

Note that "The Former Yugoslav Republic of Macedonia" was listed incorrectly in the sheetnode as simply "Macedonia."  This is not how it was listed in the taxonomy.

Please would you look into this?

Thanks,

**Comment by wiegoglobal** [comment]
Hi Gary,

This issue also has not been resolved.

Thanks,

Pat

**Comment by garygoldman** [comment]
Dear Patricia,

This issue has been fixed. There were different name of the countries in the shapefile and in the region taxonomy that caused the issue.

**Comment by wiegoglobal** [comment]
Looks good, thanks.
