### ISSUE TITLE
Two countries not colored on landing page map

### ISSUE THREAD

**Issue by wiegoglobal** [WIEGO-Global/wiegodashboard#27]
1. "the state of palestine"

and

2. "the former yugoslav republic of macedonia"

They aren't on the landing page map.
I have not checked the statistics map or wiego presence map (data for item 2)
I have not checked the statistics map for item 1

**Comment by wiegoglobal** [comment]
Hi Gary,

This issue appears to still be unresolved.

**Comment by garygoldman** [comment]
Dear Patricia,

This issue has been fixed. There were different name of the countries in the shapefile and in the region taxonomy that caused the issue.

**Comment by wiegoglobal** [comment]
Looks good, thanks.
